### ISSUE TITLE
Not playing themes 

### ISSUE THREAD

**Issue by Dhop84** [latts9923/script.tvtunes#2]
Forgive me if this has been asked a million times but I've added tv tunes to Aeon MQ7 skin and downloaded some themes, they play fine just before they download and with tv tunes screensaver but don't play when I go onto the film or tv series?

**Comment by robwebset** [comment]
Hi,
Please can you provide the following.
Which version of Kodi are you running?
Which version of TvTunes are you running?
Does it work OK in Confluence?
Please can you provide a log (With TvTunes and System logging enabled) where the system starts up, go go to the location you expect the theme to be played (then at that point grab the log and post a link to it here).

https://github.com/robwebset/script.tvtunes/wiki#Debugging

Thanks
Rob

**Comment by Dhop84** [comment]
I'm pretty sure that its because I'm using PlexKodiConnect addon . Im using kodi jarvis and confluence, When I download a theme, the theme goes to a place that doesn't even exist, well not on my computer anyway, I've tried to store the themes in a custom place and that still doesn't work, so I'm pretty confident its because of PlexKodiConnect, are you familiar with that addon?

**Comment by robwebset** [comment]
No, I don't know anything about that addon - if you wanted to post a link to a debug log then I can see if there are any hints in the log file (It may just be a small tweak required to get it going for you (but won't know until I can follow things through in a log (Maybe even post a log form when you download the theme)

Thanks
Rob

**Comment by Dhop84** [comment]
Ok cheers buddy, I've not done event logging before so bare with me

**Comment by Dhop84** [comment]
I think I've done it right, I've deleted any sensitive plex info. https://mega.nz/#!nplk2LxY!7ajyvvuLROHap7q7WS4KK1IbTZkQmDExtQYOAciEEIc

**Comment by robwebset** [comment]
I'm afraid there is no debugging enabled in that log. You'll need to enable Kodi logging via the System settings, and enable debug in the TvTunes settings.

**Comment by Dhop84** [comment]
OK I'll try again

**Comment by robwebset** [comment]
Just a shot in the dark - but if PlexKodiConnector works the same sort of way as Emby, you could try setting "Store tunes in a custom path" in the TvTunes setting

https://github.com/robwebset/script.tvtunes/wiki#File_System

And see if that solves things for you.
Rob

**Comment by Dhop84** [comment]
Ive tried that and it didnt work. https://mega.nz/#!XkcwUDYR!ypX1zTuLJptEpJuUC5TJXtz5e45RF1NaKF2cYnyiGlw

**Comment by robwebset** [comment]
Thanks for the log, I do have something it would be good for you to try. I think that the existing version of TvTunes is not detecting that you have navigated into what PlexKodiConnector sees as an area it should play themes for, please can you try the following and let me know if you have any luck:

https://drive.google.com/file/d/0B1v3j95wKopxS05XaHk1Q3MtN28/view?usp=sharing

Thanks
Rob

**Comment by Dhop84** [comment]
Hi Rob thanks but it didnt work I've got another log for you if you wouldn't taking another look?
https://mega.nz/#!y8lWVYbR!yjYZMWkm6H8wRT7P29Ja_fZj0vTLMoN5yHripzT9sH4

**Comment by robwebset** [comment]
I did some googling and I think there may have been changes to PlexKodiConnector, some people saying things didn't work for a while, then got it working, did you want to take a look here and see if your settings match:

http://forums.plex.tv/discussion/comment/1239155/#Comment_1238137

Thanks
Rob

**Comment by robwebset** [comment]
Hi Dhop84,

I was going to close this for now, it may be worth you posting on the PlexKodiConnector forum to see if they have any suggestions - it's not an addon I use so I'm not sure what more I can do. Let me know if there is something specific you'd like me to look at (Just re-open this if needed)

Thanks
Rob

**Comment by Dhop84** [comment]
No worries buddy, I appreciate the time you've taken to look at it, I"ll ask in the forum and if I find anything I'll let you no  Friday, 02 December 2016, 10:20a.m. +00:00 from Rob  notifications@github.com :
