### ISSUE TITLE
Tv tunes not working in Openelec 7.0 Kodi 16.1

### ISSUE THREAD

**Issue by brimur** [latts9923/script.tvtunes#4]
Hi, I upgraded Openelec to version 7 recently and noticed the tv tunes no longer were playing. I am using version 100.5.3. I added the urepo but I get and error saying it cant be contacted when I try to install from it. If I go into the Program Add Ons and open TVTunes and go to TV Shows I can see it detects the tvtune in the folder and plays it but when I go into the Tv Shows folder itself nothing plays. I tried downgrading to version 6.something but it just threw up the message about not being in the official repo any more when I go into the TV Shows folder. Any idea what it might be, could be on my end too after the upgrade. 
Cheers

**Comment by robwebset** [comment]
TvTunes will not work without URepo installed, and if you have URepo installed then you should be getting v100.5.4.

Thanks
Rob
