### ISSUE TITLE
Continue work on Add-on

### ISSUE THREAD

**Issue by latts9923** [latts9923/script.tvtunes#6]
Hello,

I would like to pick up where you left off with this Add-on. I still use this with my MQ 7 Leia Mod.

Thanks, Jeff

**Comment by robwebset** [comment]
Sounds good, I will transfer the addon over to you

**Comment by robwebset** [comment]
Just remembered there is also screensaver.tvtunes that works with tvtunes, so transferred that as well :)

**Comment by latts9923** [comment]
I've never used the TVTunes Screensaver...I'll give it a look. Thanks sir!
